[FRONT_TEMP]
algo_type        virtual
trip_sensor      msm-therm
thresholds        -18000
thresholds_clr    -20000
sensors          msm-therm pa0-therm quiet-therm mchg-therm pa1-therm
weights          18 5 55 17 5
offsets          -4000 0 0 0 0
sampling         2000
math             0
sys_temp

[REPORT-FRONT-TEMP]
algo_type        monitor
sampling         300000
sensor           FRONT_TEMP
thresholds       42000
thresholds_clr   40000
actions          report
action_info      1

[FUSE_TEMP]
algo_type        virtual
trip_sensor      msm-therm
thresholds       -18000
thresholds_clr   -20000
sensors          msm-therm pa0-therm quiet-therm mchg-therm pa1-therm
weights          18 5 55 17 5
offsets          0 0 0 0 0
sampling         2000
math             0
sys_temp

[BACK_TEMP]
algo_type        virtual
trip_sensor      msm-therm
thresholds       -18000
thresholds_clr   -20000
sensors          msm-therm quiet-therm mchg-therm
weights          15 56 29
offsets          -4000 0 0
sampling         2000
math             0
sys_temp

[REPORT-BACK-TEMP]
algo_type        monitor
sampling         300000
sensor           BACK_TEMP
thresholds       42000
thresholds_clr   40000
actions          report
action_info      1

[MON-MSM-CPU0]
algo_type        monitor
sampling         2000
sensor           FUSE_TEMP
thresholds       42000 45000 48000
thresholds_clr   39000 42000 45000
actions          cpu0 cpu0 cpu0
action_info      1670400 1459200 1228800

[MON-MSM-CPU3]
algo_type        monitor
sampling         2000
sensor           FUSE_TEMP
thresholds       34000 37000 40000 42000 44000 48000
thresholds_clr   31000 34000 37000 40000 42000 44000
actions          cpu3 cpu3 cpu3 cpu3 cpu3 cpu3
action_info      1785600 1536000 1286400 1171200 1056000 940800

[MON-MSM-CPU7]
algo_type        monitor
sampling         2000
sensor           FUSE_TEMP
thresholds       33000 36000 39000 42000 45000 48000
thresholds_clr   30000 33000 36000 39000 42000 45000
actions          cpu7 cpu7 cpu7 cpu7 cpu7 cpu7
action_info      1593600 1248000 1132800 998400 883200 768000

[MON-MSM-GPU]
algo_type        monitor
sampling         2000
sensor           FUSE_TEMP
thresholds       36000 39000 41000 44000 48000
thresholds_clr   34000 36000 39000 41000 44000
actions          gpu gpu gpu gpu gpu
action_info      475000000 348000000 295000000 220000000 150000000
